# Generated by Django 3.2.4 on 2021-06-28 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('In', 'Ingreso'), ('Ga', 'Gasto')], default='Ga', max_length=2)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_personal_economy.cuenta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
