# Generated by Django 3.2.4 on 2021-08-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_personal_economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='api_personal_economy.cuenta'),
        ),
    ]
