# Generated by Django 3.2.4 on 2021-09-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_personal_economy', '0002_alter_operacion_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
