# Generated by Django 3.2.8 on 2024-02-24 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_personal_economy', '0005_auto_20240224_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Operacion',
            new_name='Operation',
        ),
    ]
